import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ExternalScript from "./csp-layout";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = headers().get('x-nonce') ?? ""

  return (
    <html lang="en">
     <head nonce={nonce}>
        <ExternalScript />
      </head>
      <body data-nonce={nonce} className={inter.className}>{children}</body>
    </html>
  );
}
