import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = headers().get("x-nonce") || "";

  return (
    <html lang="en">
      <Script
      nonce={nonce}
      strategy="lazyOnload"
      data-domain="my-nextjs14-with-csp.vercel.app"
      src="https://plausible.io/js/script.js"
    />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
